spring:
  application:
    name: my-spring-boot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://154.8.142.48:3306/spring_ly?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: admin123
#logging:
#  file:
#    path: /spring/log   #在当前磁盘的根路径下创建spring文件夹和里面的log文件夹；使用 spring.log作为默认文件